### Input
# input rgba image path (default to None, can be load in GUI too)
input: 
# input text prompt (default to None, can be input in GUI too)
prompt:
negative_prompt:
# input mesh for stage 2 (auto-search from stage 1 output path if None)
mesh:
# estimated elevation angle for input image 
elevation: 0
# reference image resolution
ref_size: 256
# density thresh for mesh extraction
density_thresh: 1

### Output
outdir: sync_logs
mesh_format: obj
save_path: ???

### Training
# training stage (0: coarse, 1: refine)
stage: 0
# use mvdream instead of sd 2.1
mvdream: False
# use imagedream
imagedream: False
# use stable-zero123 instead of zero123-xl
stable_zero123: False 
# guidance loss weights (0 to disable)
lambda_sd: 0
lambda_zero123: 0
lambda_syncdreamer: 1  # SyncDreamer损失权重
# warmup rgb supervision for image-to-3d
warmup_rgb_loss: True
# training batch size per iter
batch_size: 1
# training iterations for stage 1
iters: 500
# whether to linearly anneal timestep
anneal_timestep: True
# training iterations for stage 2
iters_refine: 50
# training camera radius
radius: 2
# training camera fovy
fovy: 49.1 # align with zero123 rendering setting
# training camera min elevation
min_ver: -30
# training camera max elevation
max_ver: 30
# checkpoint to load for stage 1 (should be a ply file)
load:
# whether allow geom training in stage 2
train_geo: False
# prob to invert background color during training
invert_bg_prob: 0.5

### SyncDreamer specific parameters
syncdreamer_cfg_path: configs/syncdreamer.yaml
syncdreamer_ckpt_path: ckpt/syncdreamer-pretrain.ckpt
syncdreamer_crop_size: 200
syncdreamer_cfg_scale: 2.0
syncdreamer_batch_view_num: 8

### GUI
gui: False
force_cuda_rast: False
# GUI resolution
H: 800
W: 800

### Gaussian splatting
num_pts: 5000
sh_degree: 0
position_lr_init: 0.001
position_lr_final: 0.00002
position_lr_delay_mult: 0.02
position_lr_max_steps: 500
feature_lr: 0.01
opacity_lr: 0.05
scaling_lr: 0.005
rotation_lr: 0.005
percent_dense: 0.01
density_start_iter: 100
density_end_iter: 400
densification_interval: 100
opacity_reset_interval: 700
densify_grad_threshold: 0.01

### Textured Mesh
geom_lr: 0.0001
texture_lr: 0.2